package com.example.csrfsc9.security;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.filter.OncePerRequestFilter;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * To log the token generated by the csrf
 */
public class CustomCsrfTokenFilter extends OncePerRequestFilter {

    @Override
    protected void doFilterInternal(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, FilterChain filterChain) throws ServletException, IOException {

        CsrfToken csrfToken= (CsrfToken) httpServletRequest.getAttribute("_csrf");
        System.out.println("Generated Token : "+csrfToken.getToken());

        filterChain.doFilter(httpServletRequest, httpServletResponse);
    }
}
